### ISSUE TITLE
Code snippet for get subscriber is not shown

### ISSUE THREAD

**Issue by davidsoderberg** [novuhq/api-docs#2]
Hi @andrewgolovanov,
I have added this code snippet:
https://github.com/novuhq/api-docs/blob/main/content/code-examples/subscribers/get.md

But it does not show on the api docs... Can you please look into why this is not working?

**Comment by andrewgolovanov** [comment]
Hi @davidsoderberg !
I think I figured out what the reason is :sparkles:

We get links as - `/v1/subscribers/{subscriberId}` on input from Swagger and use as an identifier to filter examples, instead of `/v1/subscribers/:subscriberId `- which we show on pages 

I added a fix that allows you to use your variant when specifying an `id`
